"""add address_id & snapshot to orders

Revision ID: 30053c36f940
Revises: a44d1a440376
Create Date: 2025-05-10 20:29:44.415611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30053c36f940'
down_revision: Union[str, None] = 'a44d1a440376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('street', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('postal_code', sa.String(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'street')
    # ### end Alembic commands ###
